name: Build and Publish Python Package

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Test Python Package"
    types:
      - completed
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Build package
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build -w

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: image_gallery
          path: dist/*.whl

  publish:
    needs:
      - build
    runs-on: ubuntu-latest

    steps:
      - name: Download wheel
        uses: actions/download-artifact@v4
        with:
          path: wheels
          merge-multiple: true

      - name: Connect to Tailnet
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: latest
          use-cache: 'true'

      - name: Publish to private PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.PYPI_USER }}
          password: ${{ secrets.PYPI_PWD }}
          repository-url: ${{ secrets.PYPI_URL }}
          packages-dir: wheels
          verbose: true
