name: Push Image to GitHub Container Registry

on:
  workflow_run:
    workflows:
      - "Build and Publish Python Package"
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install package and its dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools-scm
          pip install .

      - name: Extract version
        id: extract_version
        run: |
          package_version=$(python -m setuptools_scm)
          docker_version=$(echo "$package_version" | tr '+' '-')
          echo "docker_version=$docker_version" >> $GITHUB_OUTPUT

      # Set up QEMU for cross-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set docker image tag
        id: set_tag
        run: |
          # Add latest tag only for stable releases, otherwise add dev tag
          if [[ "${{ github.event.workflow_run.event }}" == "release" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          else
            echo "tag=dev" >> $GITHUB_OUTPUT
          fi

      - name: Lower repository owner
        id: lower_owner
        run: echo "lower_owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ghcr.io/${{ steps.lower_owner.outputs.lower_owner }}/simple-image-gallery:${{ steps.extract_version.outputs.docker_version }}
            ghcr.io/${{ steps.lower_owner.outputs.lower_owner }}/simple-image-gallery:${{ steps.set_tag.outputs.tag }}